version: '3'
services:
  app:
    image: ruby:2.6.6
    volumes:
      - .:/cli_rpn_calculator
    working_dir: /cli_rpn_calculator
    command: ruby start.rb
    environment:
      PRODUCTION: 'true'
