name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby 2.6.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.6

    - name: Bundle
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: RuboCop
      run: |
        bundle exec rubocop

    - name: RSpec
      run: |
        bundle exec rspec spec
